// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.entity;

import com.ssigdl.sirc.entity.SsiCheque;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SsiCheque_Roo_Configurable {
    
    declare @type: SsiCheque: @Configurable;
    
}
