// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.entity;

import com.ssigdl.sirc.entity.SsiFactura;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SsiFactura_Roo_Configurable {
    
    declare @type: SsiFactura: @Configurable;
    
}
