// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiArticuloUnidadMedidaDataOnDemand;
import com.ssigdl.sirc.entity.SsiArticuloUnidadMedida;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.stereotype.Component;

privileged aspect SsiArticuloUnidadMedidaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SsiArticuloUnidadMedidaDataOnDemand: @Component;
    
    private Random SsiArticuloUnidadMedidaDataOnDemand.rnd = new SecureRandom();
    
    private List<SsiArticuloUnidadMedida> SsiArticuloUnidadMedidaDataOnDemand.data;
    
    public SsiArticuloUnidadMedida SsiArticuloUnidadMedidaDataOnDemand.getNewTransientSsiArticuloUnidadMedida(int index) {
        SsiArticuloUnidadMedida obj = new SsiArticuloUnidadMedida();
        setArumDescripcion(obj, index);
        return obj;
    }
    
    public void SsiArticuloUnidadMedidaDataOnDemand.setArumDescripcion(SsiArticuloUnidadMedida obj, int index) {
        String arumDescripcion = "arumDescripcion_" + index;
        if (arumDescripcion.length() > 255) {
            arumDescripcion = arumDescripcion.substring(0, 255);
        }
        obj.setArumDescripcion(arumDescripcion);
    }
    
    public SsiArticuloUnidadMedida SsiArticuloUnidadMedidaDataOnDemand.getSpecificSsiArticuloUnidadMedida(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SsiArticuloUnidadMedida obj = data.get(index);
        Integer id = obj.getArumId();
        return SsiArticuloUnidadMedida.findSsiArticuloUnidadMedida(id);
    }
    
    public SsiArticuloUnidadMedida SsiArticuloUnidadMedidaDataOnDemand.getRandomSsiArticuloUnidadMedida() {
        init();
        SsiArticuloUnidadMedida obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getArumId();
        return SsiArticuloUnidadMedida.findSsiArticuloUnidadMedida(id);
    }
    
    public boolean SsiArticuloUnidadMedidaDataOnDemand.modifySsiArticuloUnidadMedida(SsiArticuloUnidadMedida obj) {
        return false;
    }
    
    public void SsiArticuloUnidadMedidaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SsiArticuloUnidadMedida.findSsiArticuloUnidadMedidaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SsiArticuloUnidadMedida' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SsiArticuloUnidadMedida>();
        for (int i = 0; i < 10; i++) {
            SsiArticuloUnidadMedida obj = getNewTransientSsiArticuloUnidadMedida(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
