// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiCategoriaDataOnDemand;
import com.ssigdl.sirc.domain.SsiCategoriaIntegrationTest;
import com.ssigdl.sirc.entity.SsiCategoria;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiCategoriaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiCategoriaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiCategoriaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiCategoriaIntegrationTest: @Transactional;
    
    @Autowired
    SsiCategoriaDataOnDemand SsiCategoriaIntegrationTest.dod;
    
    @Test
    public void SsiCategoriaIntegrationTest.testCountSsiCategorias() {
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to initialize correctly", dod.getRandomSsiCategoria());
        long count = SsiCategoria.countSsiCategorias();
        Assert.assertTrue("Counter for 'SsiCategoria' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiCategoriaIntegrationTest.testFindSsiCategoria() {
        SsiCategoria obj = dod.getRandomSsiCategoria();
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to initialize correctly", obj);
        Integer id = obj.getCatId();
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to provide an identifier", id);
        obj = SsiCategoria.findSsiCategoria(id);
        Assert.assertNotNull("Find method for 'SsiCategoria' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiCategoria' returned the incorrect identifier", id, obj.getCatId());
    }
    
    @Test
    public void SsiCategoriaIntegrationTest.testFindAllSsiCategorias() {
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to initialize correctly", dod.getRandomSsiCategoria());
        long count = SsiCategoria.countSsiCategorias();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiCategoria', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiCategoria> result = SsiCategoria.findAllSsiCategorias();
        Assert.assertNotNull("Find all method for 'SsiCategoria' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiCategoria' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiCategoriaIntegrationTest.testFindSsiCategoriaEntries() {
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to initialize correctly", dod.getRandomSsiCategoria());
        long count = SsiCategoria.countSsiCategorias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiCategoria> result = SsiCategoria.findSsiCategoriaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiCategoria' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiCategoria' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiCategoriaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to initialize correctly", dod.getRandomSsiCategoria());
        SsiCategoria obj = dod.getNewTransientSsiCategoria(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiCategoria' identifier to be null", obj.getCatId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiCategoria' identifier to no longer be null", obj.getCatId());
    }
    
    @Test
    public void SsiCategoriaIntegrationTest.testRemove() {
        SsiCategoria obj = dod.getRandomSsiCategoria();
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to initialize correctly", obj);
        Integer id = obj.getCatId();
        Assert.assertNotNull("Data on demand for 'SsiCategoria' failed to provide an identifier", id);
        obj = SsiCategoria.findSsiCategoria(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiCategoria' with identifier '" + id + "'", SsiCategoria.findSsiCategoria(id));
    }
    
}
