// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiCategoriaTemporalDataOnDemand;
import com.ssigdl.sirc.entity.SsiCategoriaTemporal;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.stereotype.Component;

privileged aspect SsiCategoriaTemporalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SsiCategoriaTemporalDataOnDemand: @Component;
    
    private Random SsiCategoriaTemporalDataOnDemand.rnd = new SecureRandom();
    
    private List<SsiCategoriaTemporal> SsiCategoriaTemporalDataOnDemand.data;
    
    public SsiCategoriaTemporal SsiCategoriaTemporalDataOnDemand.getNewTransientSsiCategoriaTemporal(int index) {
        SsiCategoriaTemporal obj = new SsiCategoriaTemporal();
        setCattIdHijo(obj, index);
        setCattIdPadre(obj, index);
        setCattNivel(obj, index);
        return obj;
    }
    
    public void SsiCategoriaTemporalDataOnDemand.setCattIdHijo(SsiCategoriaTemporal obj, int index) {
        Integer cattIdHijo = new Integer(index);
        obj.setCattIdHijo(cattIdHijo);
    }
    
    public void SsiCategoriaTemporalDataOnDemand.setCattIdPadre(SsiCategoriaTemporal obj, int index) {
        Integer cattIdPadre = new Integer(index);
        obj.setCattIdPadre(cattIdPadre);
    }
    
    public void SsiCategoriaTemporalDataOnDemand.setCattNivel(SsiCategoriaTemporal obj, int index) {
        Integer cattNivel = new Integer(index);
        obj.setCattNivel(cattNivel);
    }
    
    public SsiCategoriaTemporal SsiCategoriaTemporalDataOnDemand.getSpecificSsiCategoriaTemporal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SsiCategoriaTemporal obj = data.get(index);
        Integer id = obj.getCattId();
        return SsiCategoriaTemporal.findSsiCategoriaTemporal(id);
    }
    
    public SsiCategoriaTemporal SsiCategoriaTemporalDataOnDemand.getRandomSsiCategoriaTemporal() {
        init();
        SsiCategoriaTemporal obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getCattId();
        return SsiCategoriaTemporal.findSsiCategoriaTemporal(id);
    }
    
    public boolean SsiCategoriaTemporalDataOnDemand.modifySsiCategoriaTemporal(SsiCategoriaTemporal obj) {
        return false;
    }
    
    public void SsiCategoriaTemporalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SsiCategoriaTemporal.findSsiCategoriaTemporalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SsiCategoriaTemporal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SsiCategoriaTemporal>();
        for (int i = 0; i < 10; i++) {
            SsiCategoriaTemporal obj = getNewTransientSsiCategoriaTemporal(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
