// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiCategoriaTemporalDataOnDemand;
import com.ssigdl.sirc.domain.SsiCategoriaTemporalIntegrationTest;
import com.ssigdl.sirc.entity.SsiCategoriaTemporal;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiCategoriaTemporalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiCategoriaTemporalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiCategoriaTemporalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiCategoriaTemporalIntegrationTest: @Transactional;
    
    @Autowired
    SsiCategoriaTemporalDataOnDemand SsiCategoriaTemporalIntegrationTest.dod;
    
    @Test
    public void SsiCategoriaTemporalIntegrationTest.testCountSsiCategoriaTemporals() {
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to initialize correctly", dod.getRandomSsiCategoriaTemporal());
        long count = SsiCategoriaTemporal.countSsiCategoriaTemporals();
        Assert.assertTrue("Counter for 'SsiCategoriaTemporal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiCategoriaTemporalIntegrationTest.testFindSsiCategoriaTemporal() {
        SsiCategoriaTemporal obj = dod.getRandomSsiCategoriaTemporal();
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to initialize correctly", obj);
        Integer id = obj.getCattId();
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to provide an identifier", id);
        obj = SsiCategoriaTemporal.findSsiCategoriaTemporal(id);
        Assert.assertNotNull("Find method for 'SsiCategoriaTemporal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiCategoriaTemporal' returned the incorrect identifier", id, obj.getCattId());
    }
    
    @Test
    public void SsiCategoriaTemporalIntegrationTest.testFindAllSsiCategoriaTemporals() {
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to initialize correctly", dod.getRandomSsiCategoriaTemporal());
        long count = SsiCategoriaTemporal.countSsiCategoriaTemporals();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiCategoriaTemporal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiCategoriaTemporal> result = SsiCategoriaTemporal.findAllSsiCategoriaTemporals();
        Assert.assertNotNull("Find all method for 'SsiCategoriaTemporal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiCategoriaTemporal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiCategoriaTemporalIntegrationTest.testFindSsiCategoriaTemporalEntries() {
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to initialize correctly", dod.getRandomSsiCategoriaTemporal());
        long count = SsiCategoriaTemporal.countSsiCategoriaTemporals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiCategoriaTemporal> result = SsiCategoriaTemporal.findSsiCategoriaTemporalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiCategoriaTemporal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiCategoriaTemporal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiCategoriaTemporalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to initialize correctly", dod.getRandomSsiCategoriaTemporal());
        SsiCategoriaTemporal obj = dod.getNewTransientSsiCategoriaTemporal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiCategoriaTemporal' identifier to be null", obj.getCattId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiCategoriaTemporal' identifier to no longer be null", obj.getCattId());
    }
    
    @Test
    public void SsiCategoriaTemporalIntegrationTest.testRemove() {
        SsiCategoriaTemporal obj = dod.getRandomSsiCategoriaTemporal();
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to initialize correctly", obj);
        Integer id = obj.getCattId();
        Assert.assertNotNull("Data on demand for 'SsiCategoriaTemporal' failed to provide an identifier", id);
        obj = SsiCategoriaTemporal.findSsiCategoriaTemporal(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiCategoriaTemporal' with identifier '" + id + "'", SsiCategoriaTemporal.findSsiCategoriaTemporal(id));
    }
    
}
