// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiEmpresaDataOnDemand;
import com.ssigdl.sirc.domain.SsiEmpresaIntegrationTest;
import com.ssigdl.sirc.entity.SsiEmpresa;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiEmpresaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiEmpresaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiEmpresaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiEmpresaIntegrationTest: @Transactional;
    
    @Autowired
    SsiEmpresaDataOnDemand SsiEmpresaIntegrationTest.dod;
    
    @Test
    public void SsiEmpresaIntegrationTest.testCountSsiEmpresas() {
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to initialize correctly", dod.getRandomSsiEmpresa());
        long count = SsiEmpresa.countSsiEmpresas();
        Assert.assertTrue("Counter for 'SsiEmpresa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiEmpresaIntegrationTest.testFindSsiEmpresa() {
        SsiEmpresa obj = dod.getRandomSsiEmpresa();
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to initialize correctly", obj);
        Integer id = obj.getEmpId();
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to provide an identifier", id);
        obj = SsiEmpresa.findSsiEmpresa(id);
        Assert.assertNotNull("Find method for 'SsiEmpresa' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiEmpresa' returned the incorrect identifier", id, obj.getEmpId());
    }
    
    @Test
    public void SsiEmpresaIntegrationTest.testFindAllSsiEmpresas() {
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to initialize correctly", dod.getRandomSsiEmpresa());
        long count = SsiEmpresa.countSsiEmpresas();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiEmpresa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiEmpresa> result = SsiEmpresa.findAllSsiEmpresas();
        Assert.assertNotNull("Find all method for 'SsiEmpresa' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiEmpresa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiEmpresaIntegrationTest.testFindSsiEmpresaEntries() {
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to initialize correctly", dod.getRandomSsiEmpresa());
        long count = SsiEmpresa.countSsiEmpresas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiEmpresa> result = SsiEmpresa.findSsiEmpresaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiEmpresa' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiEmpresa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiEmpresaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to initialize correctly", dod.getRandomSsiEmpresa());
        SsiEmpresa obj = dod.getNewTransientSsiEmpresa(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiEmpresa' identifier to be null", obj.getEmpId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiEmpresa' identifier to no longer be null", obj.getEmpId());
    }
    
    @Test
    public void SsiEmpresaIntegrationTest.testRemove() {
        SsiEmpresa obj = dod.getRandomSsiEmpresa();
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to initialize correctly", obj);
        Integer id = obj.getEmpId();
        Assert.assertNotNull("Data on demand for 'SsiEmpresa' failed to provide an identifier", id);
        obj = SsiEmpresa.findSsiEmpresa(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiEmpresa' with identifier '" + id + "'", SsiEmpresa.findSsiEmpresa(id));
    }
    
}
