// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiFacturaArticuloRelDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SsiFacturaArticuloRelDataOnDemand_Roo_Configurable {
    
    declare @type: SsiFacturaArticuloRelDataOnDemand: @Configurable;
    
}
