// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiFacturaServicioRelDataOnDemand;
import com.ssigdl.sirc.domain.SsiFacturaServicioRelIntegrationTest;
import com.ssigdl.sirc.entity.SsiFacturaServicioRel;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiFacturaServicioRelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiFacturaServicioRelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiFacturaServicioRelIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiFacturaServicioRelIntegrationTest: @Transactional;
    
    @Autowired
    SsiFacturaServicioRelDataOnDemand SsiFacturaServicioRelIntegrationTest.dod;
    
    @Test
    public void SsiFacturaServicioRelIntegrationTest.testCountSsiFacturaServicioRels() {
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to initialize correctly", dod.getRandomSsiFacturaServicioRel());
        long count = SsiFacturaServicioRel.countSsiFacturaServicioRels();
        Assert.assertTrue("Counter for 'SsiFacturaServicioRel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiFacturaServicioRelIntegrationTest.testFindSsiFacturaServicioRel() {
        SsiFacturaServicioRel obj = dod.getRandomSsiFacturaServicioRel();
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to initialize correctly", obj);
        Integer id = obj.getFaseId();
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to provide an identifier", id);
        obj = SsiFacturaServicioRel.findSsiFacturaServicioRel(id);
        Assert.assertNotNull("Find method for 'SsiFacturaServicioRel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiFacturaServicioRel' returned the incorrect identifier", id, obj.getFaseId());
    }
    
    @Test
    public void SsiFacturaServicioRelIntegrationTest.testFindAllSsiFacturaServicioRels() {
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to initialize correctly", dod.getRandomSsiFacturaServicioRel());
        long count = SsiFacturaServicioRel.countSsiFacturaServicioRels();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiFacturaServicioRel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiFacturaServicioRel> result = SsiFacturaServicioRel.findAllSsiFacturaServicioRels();
        Assert.assertNotNull("Find all method for 'SsiFacturaServicioRel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiFacturaServicioRel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiFacturaServicioRelIntegrationTest.testFindSsiFacturaServicioRelEntries() {
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to initialize correctly", dod.getRandomSsiFacturaServicioRel());
        long count = SsiFacturaServicioRel.countSsiFacturaServicioRels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiFacturaServicioRel> result = SsiFacturaServicioRel.findSsiFacturaServicioRelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiFacturaServicioRel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiFacturaServicioRel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiFacturaServicioRelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to initialize correctly", dod.getRandomSsiFacturaServicioRel());
        SsiFacturaServicioRel obj = dod.getNewTransientSsiFacturaServicioRel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiFacturaServicioRel' identifier to be null", obj.getFaseId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiFacturaServicioRel' identifier to no longer be null", obj.getFaseId());
    }
    
    @Test
    public void SsiFacturaServicioRelIntegrationTest.testRemove() {
        SsiFacturaServicioRel obj = dod.getRandomSsiFacturaServicioRel();
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to initialize correctly", obj);
        Integer id = obj.getFaseId();
        Assert.assertNotNull("Data on demand for 'SsiFacturaServicioRel' failed to provide an identifier", id);
        obj = SsiFacturaServicioRel.findSsiFacturaServicioRel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiFacturaServicioRel' with identifier '" + id + "'", SsiFacturaServicioRel.findSsiFacturaServicioRel(id));
    }
    
}
