// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiFacturaDataOnDemand;
import com.ssigdl.sirc.domain.SsiFacturaIntegrationTest;
import com.ssigdl.sirc.entity.SsiFactura;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiFacturaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiFacturaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiFacturaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiFacturaIntegrationTest: @Transactional;
    
    @Autowired
    SsiFacturaDataOnDemand SsiFacturaIntegrationTest.dod;
    
    @Test
    public void SsiFacturaIntegrationTest.testCountSsiFacturas() {
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to initialize correctly", dod.getRandomSsiFactura());
        long count = SsiFactura.countSsiFacturas();
        Assert.assertTrue("Counter for 'SsiFactura' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiFacturaIntegrationTest.testFindSsiFactura() {
        SsiFactura obj = dod.getRandomSsiFactura();
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to initialize correctly", obj);
        Integer id = obj.getFactId();
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to provide an identifier", id);
        obj = SsiFactura.findSsiFactura(id);
        Assert.assertNotNull("Find method for 'SsiFactura' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiFactura' returned the incorrect identifier", id, obj.getFactId());
    }
    
    @Test
    public void SsiFacturaIntegrationTest.testFindAllSsiFacturas() {
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to initialize correctly", dod.getRandomSsiFactura());
        long count = SsiFactura.countSsiFacturas();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiFactura', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiFactura> result = SsiFactura.findAllSsiFacturas();
        Assert.assertNotNull("Find all method for 'SsiFactura' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiFactura' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiFacturaIntegrationTest.testFindSsiFacturaEntries() {
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to initialize correctly", dod.getRandomSsiFactura());
        long count = SsiFactura.countSsiFacturas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiFactura> result = SsiFactura.findSsiFacturaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiFactura' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiFactura' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiFacturaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to initialize correctly", dod.getRandomSsiFactura());
        SsiFactura obj = dod.getNewTransientSsiFactura(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiFactura' identifier to be null", obj.getFactId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiFactura' identifier to no longer be null", obj.getFactId());
    }
    
    @Test
    public void SsiFacturaIntegrationTest.testRemove() {
        SsiFactura obj = dod.getRandomSsiFactura();
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to initialize correctly", obj);
        Integer id = obj.getFactId();
        Assert.assertNotNull("Data on demand for 'SsiFactura' failed to provide an identifier", id);
        obj = SsiFactura.findSsiFactura(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiFactura' with identifier '" + id + "'", SsiFactura.findSsiFactura(id));
    }
    
}
