// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiServicioDataOnDemand;
import com.ssigdl.sirc.domain.SsiServicioIntegrationTest;
import com.ssigdl.sirc.entity.SsiServicio;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiServicioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiServicioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiServicioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiServicioIntegrationTest: @Transactional;
    
    @Autowired
    SsiServicioDataOnDemand SsiServicioIntegrationTest.dod;
    
    @Test
    public void SsiServicioIntegrationTest.testCountSsiServicios() {
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to initialize correctly", dod.getRandomSsiServicio());
        long count = SsiServicio.countSsiServicios();
        Assert.assertTrue("Counter for 'SsiServicio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiServicioIntegrationTest.testFindSsiServicio() {
        SsiServicio obj = dod.getRandomSsiServicio();
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to initialize correctly", obj);
        Integer id = obj.getServId();
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to provide an identifier", id);
        obj = SsiServicio.findSsiServicio(id);
        Assert.assertNotNull("Find method for 'SsiServicio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiServicio' returned the incorrect identifier", id, obj.getServId());
    }
    
    @Test
    public void SsiServicioIntegrationTest.testFindAllSsiServicios() {
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to initialize correctly", dod.getRandomSsiServicio());
        long count = SsiServicio.countSsiServicios();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiServicio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiServicio> result = SsiServicio.findAllSsiServicios();
        Assert.assertNotNull("Find all method for 'SsiServicio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiServicio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiServicioIntegrationTest.testFindSsiServicioEntries() {
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to initialize correctly", dod.getRandomSsiServicio());
        long count = SsiServicio.countSsiServicios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiServicio> result = SsiServicio.findSsiServicioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiServicio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiServicio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiServicioIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to initialize correctly", dod.getRandomSsiServicio());
        SsiServicio obj = dod.getNewTransientSsiServicio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiServicio' identifier to be null", obj.getServId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiServicio' identifier to no longer be null", obj.getServId());
    }
    
    @Test
    public void SsiServicioIntegrationTest.testRemove() {
        SsiServicio obj = dod.getRandomSsiServicio();
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to initialize correctly", obj);
        Integer id = obj.getServId();
        Assert.assertNotNull("Data on demand for 'SsiServicio' failed to provide an identifier", id);
        obj = SsiServicio.findSsiServicio(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiServicio' with identifier '" + id + "'", SsiServicio.findSsiServicio(id));
    }
    
}
