// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiTelefonoCatDataOnDemand;
import com.ssigdl.sirc.entity.SsiTelefonoCat;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.stereotype.Component;

privileged aspect SsiTelefonoCatDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SsiTelefonoCatDataOnDemand: @Component;
    
    private Random SsiTelefonoCatDataOnDemand.rnd = new SecureRandom();
    
    private List<SsiTelefonoCat> SsiTelefonoCatDataOnDemand.data;
    
    public SsiTelefonoCat SsiTelefonoCatDataOnDemand.getNewTransientSsiTelefonoCat(int index) {
        SsiTelefonoCat obj = new SsiTelefonoCat();
        setTelcDescripcion(obj, index);
        return obj;
    }
    
    public void SsiTelefonoCatDataOnDemand.setTelcDescripcion(SsiTelefonoCat obj, int index) {
        String telcDescripcion = "telcDescripcion_" + index;
        if (telcDescripcion.length() > 100) {
            telcDescripcion = telcDescripcion.substring(0, 100);
        }
        obj.setTelcDescripcion(telcDescripcion);
    }
    
    public SsiTelefonoCat SsiTelefonoCatDataOnDemand.getSpecificSsiTelefonoCat(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SsiTelefonoCat obj = data.get(index);
        Integer id = obj.getTelcId();
        return SsiTelefonoCat.findSsiTelefonoCat(id);
    }
    
    public SsiTelefonoCat SsiTelefonoCatDataOnDemand.getRandomSsiTelefonoCat() {
        init();
        SsiTelefonoCat obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getTelcId();
        return SsiTelefonoCat.findSsiTelefonoCat(id);
    }
    
    public boolean SsiTelefonoCatDataOnDemand.modifySsiTelefonoCat(SsiTelefonoCat obj) {
        return false;
    }
    
    public void SsiTelefonoCatDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SsiTelefonoCat.findSsiTelefonoCatEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SsiTelefonoCat' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SsiTelefonoCat>();
        for (int i = 0; i < 10; i++) {
            SsiTelefonoCat obj = getNewTransientSsiTelefonoCat(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
