// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiDireccionEmpresaDataOnDemand;
import com.ssigdl.sirc.domain.SsiTelefonoCatDataOnDemand;
import com.ssigdl.sirc.domain.SsiTelefonoDataOnDemand;
import com.ssigdl.sirc.entity.SsiDireccionEmpresa;
import com.ssigdl.sirc.entity.SsiTelefono;
import com.ssigdl.sirc.entity.SsiTelefonoCat;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SsiTelefonoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SsiTelefonoDataOnDemand: @Component;
    
    private Random SsiTelefonoDataOnDemand.rnd = new SecureRandom();
    
    private List<SsiTelefono> SsiTelefonoDataOnDemand.data;
    
    @Autowired
    SsiDireccionEmpresaDataOnDemand SsiTelefonoDataOnDemand.ssiDireccionEmpresaDataOnDemand;
    
    @Autowired
    SsiTelefonoCatDataOnDemand SsiTelefonoDataOnDemand.ssiTelefonoCatDataOnDemand;
    
    public SsiTelefono SsiTelefonoDataOnDemand.getNewTransientSsiTelefono(int index) {
        SsiTelefono obj = new SsiTelefono();
        setTelDireIdFk(obj, index);
        setTelTelcIdFk(obj, index);
        setTelTelefono(obj, index);
        return obj;
    }
    
    public void SsiTelefonoDataOnDemand.setTelDireIdFk(SsiTelefono obj, int index) {
        SsiDireccionEmpresa telDireIdFk = ssiDireccionEmpresaDataOnDemand.getRandomSsiDireccionEmpresa();
        obj.setTelDireIdFk(telDireIdFk);
    }
    
    public void SsiTelefonoDataOnDemand.setTelTelcIdFk(SsiTelefono obj, int index) {
        SsiTelefonoCat telTelcIdFk = ssiTelefonoCatDataOnDemand.getRandomSsiTelefonoCat();
        obj.setTelTelcIdFk(telTelcIdFk);
    }
    
    public void SsiTelefonoDataOnDemand.setTelTelefono(SsiTelefono obj, int index) {
        String telTelefono = "telTelefono_" + index;
        if (telTelefono.length() > 16) {
            telTelefono = telTelefono.substring(0, 16);
        }
        obj.setTelTelefono(telTelefono);
    }
    
    public SsiTelefono SsiTelefonoDataOnDemand.getSpecificSsiTelefono(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SsiTelefono obj = data.get(index);
        Integer id = obj.getTelId();
        return SsiTelefono.findSsiTelefono(id);
    }
    
    public SsiTelefono SsiTelefonoDataOnDemand.getRandomSsiTelefono() {
        init();
        SsiTelefono obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getTelId();
        return SsiTelefono.findSsiTelefono(id);
    }
    
    public boolean SsiTelefonoDataOnDemand.modifySsiTelefono(SsiTelefono obj) {
        return false;
    }
    
    public void SsiTelefonoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SsiTelefono.findSsiTelefonoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SsiTelefono' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SsiTelefono>();
        for (int i = 0; i < 10; i++) {
            SsiTelefono obj = getNewTransientSsiTelefono(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
