// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiTelefonoDataOnDemand;
import com.ssigdl.sirc.domain.SsiTelefonoIntegrationTest;
import com.ssigdl.sirc.entity.SsiTelefono;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiTelefonoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiTelefonoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiTelefonoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiTelefonoIntegrationTest: @Transactional;
    
    @Autowired
    SsiTelefonoDataOnDemand SsiTelefonoIntegrationTest.dod;
    
    @Test
    public void SsiTelefonoIntegrationTest.testCountSsiTelefonoes() {
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to initialize correctly", dod.getRandomSsiTelefono());
        long count = SsiTelefono.countSsiTelefonoes();
        Assert.assertTrue("Counter for 'SsiTelefono' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiTelefonoIntegrationTest.testFindSsiTelefono() {
        SsiTelefono obj = dod.getRandomSsiTelefono();
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to initialize correctly", obj);
        Integer id = obj.getTelId();
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to provide an identifier", id);
        obj = SsiTelefono.findSsiTelefono(id);
        Assert.assertNotNull("Find method for 'SsiTelefono' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiTelefono' returned the incorrect identifier", id, obj.getTelId());
    }
    
    @Test
    public void SsiTelefonoIntegrationTest.testFindAllSsiTelefonoes() {
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to initialize correctly", dod.getRandomSsiTelefono());
        long count = SsiTelefono.countSsiTelefonoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiTelefono', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiTelefono> result = SsiTelefono.findAllSsiTelefonoes();
        Assert.assertNotNull("Find all method for 'SsiTelefono' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiTelefono' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiTelefonoIntegrationTest.testFindSsiTelefonoEntries() {
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to initialize correctly", dod.getRandomSsiTelefono());
        long count = SsiTelefono.countSsiTelefonoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiTelefono> result = SsiTelefono.findSsiTelefonoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiTelefono' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiTelefono' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiTelefonoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to initialize correctly", dod.getRandomSsiTelefono());
        SsiTelefono obj = dod.getNewTransientSsiTelefono(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiTelefono' identifier to be null", obj.getTelId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiTelefono' identifier to no longer be null", obj.getTelId());
    }
    
    @Test
    public void SsiTelefonoIntegrationTest.testRemove() {
        SsiTelefono obj = dod.getRandomSsiTelefono();
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to initialize correctly", obj);
        Integer id = obj.getTelId();
        Assert.assertNotNull("Data on demand for 'SsiTelefono' failed to provide an identifier", id);
        obj = SsiTelefono.findSsiTelefono(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiTelefono' with identifier '" + id + "'", SsiTelefono.findSsiTelefono(id));
    }
    
}
