// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ssigdl.sirc.domain;

import com.ssigdl.sirc.domain.SsiTelefonoCatDataOnDemand;
import com.ssigdl.sirc.domain.SsiTelefonoCatIntegrationTest;
import com.ssigdl.sirc.entity.SsiTelefonoCat;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SsiTelefonoCatIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SsiTelefonoCatIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SsiTelefonoCatIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SsiTelefonoCatIntegrationTest: @Transactional;
    
    @Autowired
    SsiTelefonoCatDataOnDemand SsiTelefonoCatIntegrationTest.dod;
    
    @Test
    public void SsiTelefonoCatIntegrationTest.testCountSsiTelefonoCats() {
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to initialize correctly", dod.getRandomSsiTelefonoCat());
        long count = SsiTelefonoCat.countSsiTelefonoCats();
        Assert.assertTrue("Counter for 'SsiTelefonoCat' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SsiTelefonoCatIntegrationTest.testFindSsiTelefonoCat() {
        SsiTelefonoCat obj = dod.getRandomSsiTelefonoCat();
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to initialize correctly", obj);
        Integer id = obj.getTelcId();
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to provide an identifier", id);
        obj = SsiTelefonoCat.findSsiTelefonoCat(id);
        Assert.assertNotNull("Find method for 'SsiTelefonoCat' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SsiTelefonoCat' returned the incorrect identifier", id, obj.getTelcId());
    }
    
    @Test
    public void SsiTelefonoCatIntegrationTest.testFindAllSsiTelefonoCats() {
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to initialize correctly", dod.getRandomSsiTelefonoCat());
        long count = SsiTelefonoCat.countSsiTelefonoCats();
        Assert.assertTrue("Too expensive to perform a find all test for 'SsiTelefonoCat', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SsiTelefonoCat> result = SsiTelefonoCat.findAllSsiTelefonoCats();
        Assert.assertNotNull("Find all method for 'SsiTelefonoCat' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SsiTelefonoCat' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SsiTelefonoCatIntegrationTest.testFindSsiTelefonoCatEntries() {
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to initialize correctly", dod.getRandomSsiTelefonoCat());
        long count = SsiTelefonoCat.countSsiTelefonoCats();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SsiTelefonoCat> result = SsiTelefonoCat.findSsiTelefonoCatEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SsiTelefonoCat' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SsiTelefonoCat' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SsiTelefonoCatIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to initialize correctly", dod.getRandomSsiTelefonoCat());
        SsiTelefonoCat obj = dod.getNewTransientSsiTelefonoCat(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SsiTelefonoCat' identifier to be null", obj.getTelcId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SsiTelefonoCat' identifier to no longer be null", obj.getTelcId());
    }
    
    @Test
    public void SsiTelefonoCatIntegrationTest.testRemove() {
        SsiTelefonoCat obj = dod.getRandomSsiTelefonoCat();
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to initialize correctly", obj);
        Integer id = obj.getTelcId();
        Assert.assertNotNull("Data on demand for 'SsiTelefonoCat' failed to provide an identifier", id);
        obj = SsiTelefonoCat.findSsiTelefonoCat(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SsiTelefonoCat' with identifier '" + id + "'", SsiTelefonoCat.findSsiTelefonoCat(id));
    }
    
}
